source:
  type: postgresql
  uri: !env PS_DATABASE_URL

storage:
  type: postgresql
  uri: !env PS_DATABASE_URL

client_auth:
  jwks_uris:
    - !env PS_POWERSYNC_JWKS_URL

sync_rules:
  path: /config/sync-rules.yaml
